/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsAppIdRouteImport } from './routes/reviews.$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsAppIdRoute = ReviewsAppIdRouteImport.update({
  id: '/reviews/$appId',
  path: '/reviews/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviews/$appId': typeof ReviewsAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviews/$appId': typeof ReviewsAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviews/$appId': typeof ReviewsAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reviews/$appId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reviews/$appId'
  id: '__root__' | '/' | '/reviews/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewsAppIdRoute: typeof ReviewsAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$appId': {
      id: '/reviews/$appId'
      path: '/reviews/$appId'
      fullPath: '/reviews/$appId'
      preLoaderRoute: typeof ReviewsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewsAppIdRoute: ReviewsAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
